export const INCREASE_COUNTER = "INCREASE_COUNTER"


export const GET_LIST_STUDENTS = "GET_LIST_STUDENTS"
export const GET_LIST_STUDENTS_SUCCESS = "GET_LIST_STUDENTS_SUCCESS"
export const GET_LIST_STUDENTS_FAILED = "GET_LIST_STUDENTS_FAILED"

export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"